#!/usr/bin/env bash
# Script to install Nginx

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
service nginx start
sudo chown -R $USER:$USER /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
