#!/usr/bin/env bash
# Script to create a custom 404 page

apt-get -y update
apt-get -y install nginx
service nginx start
sudo chown -R "$USER":"$USER" /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html

sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"  /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/custom_404.html
sed -i "/redirect_me/ a\\\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default

sed -i "/custom_404.html;/ a\\\tadd_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-available/default

service nginx restart
