#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
backend hibaasim-backend
        balance roundrobin
        server 507787-web-01 18.209.223.158:80 check
        server 507787-web-02 54.84.59.149:80 check

frontend hibaasim-frontend
        bind *:80
        mode http
        default_backend hibaasim-backend

"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
