#!/usr/bin/env bash
# This script that displays 1 to 100 but shows:
# fizz if it is a multiple of 3
# buzz if it is a multiple of 5
# fizzbuzz if it is a multiple of both

i=1
while ((i <= 100))
do
if [ $((i%3)) == 0 ] && [ $((i%5)) == 0 ]
then
	echo FizzBuzz
elif [ $((i%3)) == 0 ]
then
	echo Fizz
elif [ $((i%5)) == 0 ]
then
	echo Buzz
else
	echo $i
fi
((i++))
done
