#!/usr/bin/env bash
# This script dislays the numbers from 1 to 20 and displays
# on the 4th iteration: "bad luck from China"
# on the 9th: "bad luck from Japan"
# on the 17th: "bad luck from Italy"

i=1
while ((i < 21))
do
echo $i
case $i in
	"4")
		echo "bad luck from China"
		;;
	"9")
		echo "bad luck from Japan"
		;;
	"17")
		echo "bad luck from Italy"
		;;
esac
((i++))
done
